# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /404.html

# Setup
title:            Huiyong Li
tagline:          'Site'
description:      'A PhD student of Informatics at Kyoto University. Research on Learning Analytics, Self-Regulated Learning, Self-Directed Learning, and Technology Enhanced Learning.'
url:              https://li-huiyong.github.io
baseurl:          https://li-huiyong.github.io/
update:           8/2019

#author:
#  name:           'Mark Otto'
#  url:            https://li-huiyong.github.io

paginate:         5

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
