# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /404.html

# Setup
title:            Huiyong Li
tagline:          'Site'
description:      'An Asst.Prof. at Research Institute for Information Technology, Kyushu University. Received Ph.D. in Informatics from Kyoto University in 2021. Research on Learning Analytics, Data Mining, Self-Regulated Learning, and Technology Enhanced Language Learning.'
url:              https://li-huiyong.github.io
baseurl:          https://li-huiyong.github.io/
update:           01/2025
avatarurl:        https://li-huiyong.github.io/resources/avatar2019.png

#author:
#  name:           'Mark Otto'
#  url:            https://li-huiyong.github.io

paginate:         5

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
